version: "3.2"

services:
  db:
    image: postgis/postgis
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: socialchange
