version: "3.2"

services:
  db:
    image: postgis/postgis
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: socialchange

  elastic:
    image: elasticsearch:7.12.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    networks:
      - elastic
    volumes:
      - elastic:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.12.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    networks:
      - elastic

volumes:
  elastic:
    driver: local

networks:
  elastic:
    driver: bridge
